class VideoItem {
  final String id;
  final String title;
  final String duration;
  final String views;
  final String uploadTime;
  final String channel;
  final String category;
  final String thumbnailUrl;
  final String description;
  final String youtubeUrl;
  final bool isFeatured;

  const VideoItem({
    required this.id,
    required this.title,
    required this.duration,
    required this.views,
    required this.uploadTime,
    required this.channel,
    required this.category,
    required this.thumbnailUrl,
    required this.description,
    required this.youtubeUrl,
    this.isFeatured = false,
  });

  String get videoId {
    if (youtubeUrl.contains('youtu.be/')) {
      return youtubeUrl.split('youtu.be/').last.split('?').first;
    }
    if (youtubeUrl.contains('watch?v=')) {
      return youtubeUrl.split('watch?v=').last.split('&').first;
    }
    return id;
  }
}

final List<VideoItem> mombeeVideos = [
  const VideoItem(
    id: 'vid-1',
    title: 'গর্ভাবস্থায় পিঠ, কোমর ও পায়ে ব্যথায় করণীয় | Pregnancy Pain Relief Tips Bangla | MomBee',
    category: 'Pregnancy Health Precautions. Add it after the 3 months of pregnancy section and general video tab will also include these',
    youtubeUrl: 'https://youtu.be/YC9tQ0RJhP0',
    duration: '11:20',
    views: '85K views',
    uploadTime: 'MomBee Health',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/YC9tQ0RJhP0/hqdefault.jpg',
    description: 'গর্ভাবস্থায় পিঠ, কোমর ও পায়ে ব্যথায় করণীয় ও আরাম পাওয়ার নিরাপদ উপায়সমূহ।',
    isFeatured: true,
  ),
  const VideoItem(
    id: 'vid-2',
    title: 'আপনার কথা সন্তান শুনছে না? আজই এই ৭টি ভুল শুধরে নিন! | Scientific Parenting Tips Bangla | MomBee',
    category: 'Parenting section and add this whose baby is over 4 years after every section',
    youtubeUrl: 'https://youtu.be/Lgyzo0t6KVk',
    duration: '09:45',
    views: '120K views',
    uploadTime: 'MomBee Parenting',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/Lgyzo0t6KVk/hqdefault.jpg',
    description: 'সন্তানের সাথে কার্যকর যোগাযোগের বৈজ্ঞানিক প্যারেন্টিং টিপস।',
  ),
  const VideoItem(
    id: 'vid-3',
    title: 'গর্ভাবস্থার প্রথম ৩ মাসে কী খাবেন আর কী খাবেন না? | First Trimester Pregnancy Guide',
    category: 'Pregnancy',
    youtubeUrl: 'https://youtu.be/TMzWkui9KTU',
    duration: '08:15',
    views: '95K views',
    uploadTime: 'MomBee Guide',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/TMzWkui9KTU/hqdefault.jpg',
    description: 'প্রথম ট্রাইমেস্টারে প্রয়োজনীয় পুষ্টি এবং নিষিদ্ধ খাবারের সঠিক তালিকা।',
  ),
  const VideoItem(
    id: 'vid-4',
    title: 'গর্ভাবস্থায় এই ৬টি খাবার সন্তানকে করবে বুদ্ধিমান ও সুস্থ! | গর্ভবতী মায়ের খাবার তালিকা',
    category: 'Pregnancy Foods Nutrition',
    youtubeUrl: 'https://youtu.be/cVjAW7XZc5E',
    duration: '10:30',
    views: '140K views',
    uploadTime: 'MomBee Nutrition',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/cVjAW7XZc5E/hqdefault.jpg',
    description: 'গর্ভস্থ শিশুর মস্তিষ্কের বিকাশ ও শারীরিক সুস্থতার জন্য ৬টি সুপারফুড।',
  ),
  const VideoItem(
    id: 'vid-5',
    title: 'বাচ্চা নেওয়ার আগে স্বামী-স্ত্রীর ১০টি জরুরি প্রস্তুতি|  | Pregnancy Planning Tips | MomBee',
    category: 'Pre-Pregnancy Tips',
    youtubeUrl: 'https://youtu.be/bvIFvTUzkHQ',
    duration: '12:10',
    views: '110K views',
    uploadTime: 'MomBee Planning',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/bvIFvTUzkHQ/hqdefault.jpg',
    description: 'গর্ভধারণের পূর্বে স্বামী-স্ত্রীর স্বাস্থ্য পরীক্ষা ও মানসিক প্রস্তুতি।',
  ),
  const VideoItem(
    id: 'vid-6',
    title: 'বাবা-মায়ের জন্য সতর্কবার্তা রামিসার ঘটনা থেকে শিক্ষা! Parenting Tips! MomBee',
    category: 'Parenting Tips',
    youtubeUrl: 'https://youtu.be/qFAiEyQD-Ik',
    duration: '07:50',
    views: '65K views',
    uploadTime: 'MomBee Care',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/qFAiEyQD-Ik/hqdefault.jpg',
    description: 'অভিভাবকদের জন্য বাস্তব অভিজ্ঞতা থেকে গুরুত্বপূর্ণ শিক্ষা ও সতর্কতা।',
  ),
  const VideoItem(
    id: 'vid-7',
    title: 'শিশুর প্রথম ৬ মাসের পূর্নাঙ্গ যত্ন: খাবার, টিকা ও সর্দি-কাশির সমাধান | MomBee',
    category: 'Baby Health Tips and Parenting',
    youtubeUrl: 'https://youtu.be/mHMQCswVe9g',
    duration: '14:25',
    views: '175K views',
    uploadTime: 'MomBee Pediatrics',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/mHMQCswVe9g/hqdefault.jpg',
    description: 'নবজাতকের মাতৃদুগ্ধ পান, টিকা সময়সূচি এবং সাধারণ সমস্যার সমাধান।',
  ),
  const VideoItem(
    id: 'vid-8',
    title: 'গর্ভাবস্থায় কি খেলে বাচ্চা মেধাবী ও বুদ্ধিমান হবে ? গর্ভবতী মায়ের খাবার ও যত্ন | MomBee',
    category: 'Pregnancy Nutrition Tips',
    youtubeUrl: 'https://youtu.be/5FLx_YaKy5I',
    duration: '09:18',
    views: '130K views',
    uploadTime: 'MomBee Nutrition',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/5FLx_YaKy5I/hqdefault.jpg',
    description: 'শিশুর বুদ্ধিমত্তা বিকাশে মায়ের গর্ভাবস্থার সুষম খাদ্য তালিকা।',
  ),
  const VideoItem(
    id: 'vid-9',
    title: 'হাম কি? হামের লক্ষণ ও চিকিৎসা: দ্রুত সুস্থ হওয়ার উপায়! Measles Treatment',
    category: 'Baby Parenting',
    youtubeUrl: 'https://youtu.be/JUi26C-uEvI',
    duration: '06:40',
    views: '45K views',
    uploadTime: 'MomBee Health',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/JUi26C-uEvI/hqdefault.jpg',
    description: 'শিশুদের হামের প্রাথমিক লক্ষণ, চিকিৎসা ও সঠিক পরিচর্যা।',
  ),
  const VideoItem(
    id: 'vid-10',
    title: 'স্মার্ট বেবি ফুড গাইড | গর্ভাবস্থায় খাওয়ার সঠিক খাবার তালিকা',
    category: 'Pregnancy Nutrition',
    youtubeUrl: 'https://youtu.be/1y_WNUV_2lI',
    duration: '11:05',
    views: '92K views',
    uploadTime: 'MomBee Nutrition',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/1y_WNUV_2lI/hqdefault.jpg',
    description: 'গর্ভাবস্থায় খাওয়ার সঠিক পুষ্টিকর খাবার তালিকা ও স্মার্ট গাইড।',
  ),
  const VideoItem(
    id: 'vid-11',
    title: 'বাচ্চার ব্রেন ডেভেলপমেন্টের জন্য গর্ভাবস্থায় খেতে হবে এই ২০টি খাবার | Scientific Foods | Part 1',
    category: 'Pregnancy Nutrition',
    youtubeUrl: 'https://youtu.be/nHjoAQOI_to',
    duration: '13:50',
    views: '160K views',
    uploadTime: 'MomBee Science',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/nHjoAQOI_to/hqdefault.jpg',
    description: 'ভ্রূণের মস্তিষ্কের কোষ গঠনে সহায়তা করে এমন ২০টি বৈজ্ঞানিক খাবার।',
  ),
  const VideoItem(
    id: 'vid-12',
    title: 'নবজাতক শিশুর যত্ন কিভাবে নেবেন? নতুন মায়েদের জন্য গুরুত্বপূর্ণ টিপস | Newborn Baby Care Tips',
    category: 'Parenting Tips - Newborn',
    youtubeUrl: 'https://youtu.be/MyUN8Ah2OaQ',
    duration: '15:30',
    views: '210K views',
    uploadTime: 'MomBee Newborn',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/MyUN8Ah2OaQ/hqdefault.jpg',
    description: 'নতুন মায়েদের জন্য নবজাতকের পরিষ্কার-পরিচ্ছন্নতা ও সঠিক যত্নের পরামর্শ।',
  ),
  const VideoItem(
    id: 'vid-13',
    title: '৭ মাসের গর্ভাবস্থা: মা ও শিশুর পরিবর্তন, লক্ষণ, সমস্যা ও করণীয় । 7th Month Pregnancy',
    category: 'Pregnancy Health Tips ( 7 months section add that )',
    youtubeUrl: 'https://youtu.be/rW4jsUFL7U8',
    duration: '10:45',
    views: '88K views',
    uploadTime: 'MomBee Guide',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/rW4jsUFL7U8/hqdefault.jpg',
    description: 'সপ্তম মাসে গর্ভস্থ শিশুর বৃদ্ধি, মায়ের শারীরিক পরিবর্তন ও করণীয়।',
  ),
  const VideoItem(
    id: 'vid-14',
    title: 'সন্তান জন্মের পর মায়ের যত্ন | ডেলিভারির পর ৩ গুণ বেশি পুষ্টি কেন জরুরি? | Postpartum Care Bangla',
    category: 'Post Pregnancy Tips',
    youtubeUrl: 'https://youtu.be/3Y6Xi_Cs3zk',
    duration: '12:00',
    views: '78K views',
    uploadTime: 'MomBee Postpartum',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/3Y6Xi_Cs3zk/hqdefault.jpg',
    description: 'প্রসবোত্তর রিকভারি, মানসিক স্বাস্থ্য এবং উচ্চ পুষ্টির প্রয়োজনীয়তা।',
  ),
  const VideoItem(
    id: 'vid-15',
    title: 'ডেলিভারির আগে হসপিটাল ব্যাগে কী কী নিবেন?  Hospital bag checklist | Preparation for labor',
    category: 'Pre-delivery - Pregnancy Tips',
    youtubeUrl: 'https://youtu.be/wu7Gg4IYj4E',
    duration: '08:35',
    views: '98K views',
    uploadTime: 'MomBee Checklist',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/wu7Gg4IYj4E/hqdefault.jpg',
    description: 'হাসপাতালে যাওয়ার আগে মা ও নবজাতকের জন্য প্রয়োজনীয় জিনিসপত্রের তালিকা।',
  ),
  const VideoItem(
    id: 'vid-16',
    title: 'গর্ভবতী মায়ের খাবার তালিকা | Pregnancy Diet Bangla | Islamic & Medical Guide',
    category: 'Pregnancy Nutrition',
    youtubeUrl: 'https://youtu.be/dB7Z2RPJNnM',
    duration: '14:10',
    views: '185K views',
    uploadTime: 'MomBee Nutrition',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/dB7Z2RPJNnM/hqdefault.jpg',
    description: 'গর্ভবতী মায়ের স্বাস্থ্যসম্মত খাবার তালিকা: ইসলামিক ও চিকিৎসা গাইডলাইন।',
  ),
  const VideoItem(
    id: 'vid-17',
    title: 'নরমাল ডেলিভারির কমপ্লিট গাইড | Normal Delivery Secrets',
    category: 'Pre-delivery - Pregnancy Tips',
    youtubeUrl: 'https://youtu.be/_rD0smbi2dQ',
    duration: '16:20',
    views: '240K views',
    uploadTime: 'MomBee Labor Guide',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/_rD0smbi2dQ/hqdefault.jpg',
    description: 'সহজ ও নিরাপদ নরমাল ডেলিভারির প্রস্তুতি, শারীরিক ব্যায়াম ও পরামর্শ।',
  ),
  const VideoItem(
    id: 'vid-18',
    title: 'গর্ভবতী মায়ের খাবার তালিকা | Pregnancy Diet Bangla | Islamic & Medical Guide',
    category: 'Pregnancy Nutrition',
    youtubeUrl: 'https://youtu.be/dB7Z2RPJNnM',
    duration: '14:10',
    views: '185K views',
    uploadTime: 'MomBee Nutrition',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/dB7Z2RPJNnM/hqdefault.jpg',
    description: 'গর্ভবতী মায়ের পুষ্টিকর খাদ্যাভ্যাস ও দৈনিক খাবারের পরিমাপ।',
  ),
  const VideoItem(
    id: 'vid-19',
    title: 'আপনার শিশু কি স্কুলে যেতে চায় না ? ৫টি কারণ ও সমাধান',
    category: 'Parenting Tips ( age above 5 years )',
    youtubeUrl: 'https://youtu.be/fle9PzounNQ',
    duration: '07:25',
    views: '52K views',
    uploadTime: 'MomBee Psychology',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/fle9PzounNQ/hqdefault.jpg',
    description: 'শিশুদের স্কুল ভীতি কাটানোর মনস্তাত্ত্বিক কারণ ও মা-বাবার করণীয়।',
  ),
  const VideoItem(
    id: 'vid-20',
    title: 'জেদী বাচ্চা মানেই বুদ্ধিমান বাচ্চা | Child Psychology Explained',
    category: 'Parenting',
    youtubeUrl: 'https://youtu.be/e1Ze3_rTkZI',
    duration: '09:55',
    views: '145K views',
    uploadTime: 'MomBee Parenting',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/e1Ze3_rTkZI/hqdefault.jpg',
    description: 'জেদী স্বভাবের পেছনের মানসিক কারণ এবং ইতিবাচকভাবে পরিচালনার পদ্ধতি।',
  ),
  const VideoItem(
    id: 'vid-21',
    title: 'শীতে নবজাতক ও মায়ের যত্ন |  Winter Baby & Mom Care Tips in Bangla',
    category: 'Parenting Tips',
    youtubeUrl: 'https://youtu.be/bgHRde-PXTM',
    duration: '11:40',
    views: '115K views',
    uploadTime: 'MomBee Winter Care',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/bgHRde-PXTM/hqdefault.jpg',
    description: 'শীতের মৌসুমে নবজাতক শিশু ও প্রসূতি মায়ের বিশেষ সতর্কতা।',
  ),
  const VideoItem(
    id: 'vid-22',
    title: 'সন্তানের আত্মবিশ্বাস নষ্ট হয় এই ভুলে | Positive Parenting Tips in Bangla',
    category: 'Parenting Tips',
    youtubeUrl: 'https://youtu.be/DXfU4DEVkBA',
    duration: '08:50',
    views: '76K views',
    uploadTime: 'MomBee Positive Parenting',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/DXfU4DEVkBA/hqdefault.jpg',
    description: 'শিশুর আত্মবিশ্বাস গঠনে মা-বাবার ইতিবাচক আচরণ ও ভুল শুধরানোর উপায়।',
  ),
  const VideoItem(
    id: 'vid-23',
    title: 'সন্তানকে নিয়ন্ত্রণের সহজ কৌশল | Positive Parenting Tips in Bangla',
    category: 'Parenting Tips',
    youtubeUrl: 'https://youtu.be/QBxy5Pd2ImA',
    duration: '10:15',
    views: '89K views',
    uploadTime: 'MomBee Parenting',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/QBxy5Pd2ImA/hqdefault.jpg',
    description: 'বকাঝকা বা মারধর না করে শান্তভাবে শিশুকে সঠিক পথে রাখার নিয়ম।',
  ),
  const VideoItem(
    id: 'vid-24',
    title: 'গর্ভাবস্থায় শিশুর বৃদ্ধি ও বিকাশে প্রয়োজনীয় ৭টি খাবার',
    category: 'Pregnancy Nutrition',
    youtubeUrl: 'https://youtu.be/XHavriIZM-E',
    duration: '12:30',
    views: '135K views',
    uploadTime: 'MomBee Nutrition',
    channel: 'MomBee',
    thumbnailUrl: 'https://img.youtube.com/vi/XHavriIZM-E/hqdefault.jpg',
    description: 'গর্ভস্থ শিশুর ওজন বৃদ্ধি ও সঠিক শারীরিক গঠনে সহায়ক ৭টি অপরিহার্য খাবার।',
  ),
];

// Preserved for backward compatibility across existing references
final List<VideoItem> sampleVideos = mombeeVideos;
